name: 06 basics conditions

on:
  pull_request:
    types:
      - closed

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Print Hello World
        run: echo ${{ github.event_name }}

      - name: Print conditional message
        if: ${{ github.event.pull_request.changed_files > 1 }}
        run: echo ${{ github.event.pull_request.merged }}
